var mongoose = require('mongoose');

var collegeSchema = new mongoose.Schema({
    UNITID: Number,
    INSTNM: String,
    ADDR: String,
    CITY: String,
    STABBR: String,
    ZIP: String,
    FIPS: Number,
    OBEREG: Number,
    CHFNM: String,
    CHFTITLE: String,

    GENETELE: Number,
    FAXTELE: Number,
    EIN: Number,
    OPEID: Number,
    OPEFLAG: Number,
    WEBADDR: String,
    ADMINURL: String,
    FAIDURL: String,
    APPLURL: String,
    NPRICURL: String,

    SECTOR: Number,
    ICLEVEL: Number,
    CONTROL: Number,
    HLOFFER: Number,
    UGOFFER: Number,
    GROFFER: Number,
    HDEGOFR1: Number,
    DEGGRANT: Number,
    HBCU: Number,
    HOSPITAL: Number,

    MEDICAL: Number,
    TRIBAL: Number,
    LOCALE: Number,
    OPENPUBL: Number,
    ACT: String,
    NEWID: Number,
    DEATHYR: Number,
    CLOSEDAT: String,
    CYACTIVE: Number,
    POSTSEC: Number,

    PSEFLAG: Number,
    PSET4FLG: Number,
    RPTMTH: Number,
    IALIAS: String,
    INSTCAT: Number,
    CCBASIC: Number,
    CCIPUG: Number,
    CCIPGRAD: Number,
    CCUGPROF: Number,
    CCENRPRF: Number,

    CCSIZSET: Number,
    CARNEGIE: Number,
    LANDGRNT: Number,
    INSTSIZE: Number,
    CBSA: Number,
    CBSATYPE: Number,
    CSA: Number,
    NECTA: Number,
    F1SYSTYP: Number,
    F1SYSNAM: String,

    F1SYSCOD: Number,
    COUNTYCD: Number,
    COUNTYNM: String,
    CNGDSTCD: Number,
    LONGITUD: Number,
    LATITUDE: Number,
    enrollment: Object,
    tuition: Array
});

var College = mongoose.model('College', collegeSchema);

module.exports = College;